name: Deploy K8S Cluster

on:
  push:
    branches: ['main']
    paths: ['infra/**']
  workflow_dispatch:

jobs:
  my-debug:
    runs-on: ubuntu-22.04
    steps:
      - name: Console log
        run: echo '[LOG::gt] infra deployed'
